[workspace]

members = [
  "jotoba_bin",
  "lib/parse",
  "lib/japanese",
  "lib/models",
  "lib/cache",
  "lib/search",
  "lib/error",
  "lib/utils",
  "lib/frontend",
  "lib/api",
  "lib/import",
  "lib/localization",
]
