[package]
name = "jotoba"
version = "0.1.0"
authors = ["jojii <jojii@gmx.net>"]
edition = "2018"
license = "GPLv3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.0-beta.6"
actix-web = "4.0.0-beta.8"
argparse = "0.2.2"
env_logger = "0.9.0"
futures = "0.3.16"
serde = "1.0.126"
toml = "0.5.8"
async-std = "1.9.0"
tokio = { version = "1.9.0", features = ["macros","rt-multi-thread","sync"] }
parse = { path = "../lib/parse" }
japanese = { path = "../lib/japanese" }
models = { path = "../lib/models" }
cache = { path = "../lib/cache" }
search = { path = "../lib/search" }
error = { path = "../lib/error" }
utils = { path = "../lib/utils" }
api = { path = "../lib/api" }
frontend = { path = "../lib/frontend" }
import = { path = "../lib/import" }
config = { path = "../lib/config" }
localization = { path = "../lib/localization" }
log = "0.4.14"
sentry-actix = { version = "0.23.0", optional = true }
sentry = { version = "0.23.0", optional = true }
tokio-postgres = "0.7.2"
deadpool-postgres = "0.9.0"

[features]
tokenizer = [ "search/tokenizer", "models/tokenizer", "japanese/tokenizer" ]
sentry_error = [ "sentry", "sentry-actix", "frontend/sentry_error", "config/sentry_error" ]
default = [ "tokenizer", "sentry_error" ]
